"""
BRAIN MEMORY — MahaCellUnified Population for Brain Thoughts.

Phase 6B+7: BrainMemory is a cell population with soft relevance decay.
Each thought is a MahaCellUnified[BrainCellPayload] with prana cost.
Knowledge persists forever — only relevance ranking decays over time.
FIFO eviction (hard cap) is the only way cells are removed.

Backward-compatible API: record(), recent(), pattern_summary(),
flush(), load() all work identically to the flat FIFO.

Loaded at boot, flushed in MOKSHA. Same persistence pattern as mayor_state.json.

    Hare Krishna Hare Krishna Krishna Krishna Hare Hare
    Hare Rama   Hare Rama   Rama   Rama   Hare Hare
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger("AGENT_CITY.BRAIN_MEMORY")

_DEFAULT_MAX_ENTRIES = 24  # ~6 hours at current heartbeat rate


class BrainMemory:
    """MahaCellUnified population for brain thoughts.

    Each entry is backed by a BrainCell (MahaCellUnified[BrainCellPayload]).
    Soft relevance decay: knowledge persists, ranking changes over time.
    FIFO eviction when len > max_entries (hard cap, only removal path).

    Backward-compatible: record/recent/pattern_summary/flush/load
    all return the same dict format as the original flat FIFO.
    """

    __slots__ = ("_cells", "_entries", "_max_entries", "_path",
                 "_total_prana_spent", "_suppressed_posts")

    def __init__(
        self,
        path: Path | None = None,
        max_entries: int = _DEFAULT_MAX_ENTRIES,
    ) -> None:
        self._cells: list = []  # list[MahaCellUnified[BrainCellPayload]]
        self._entries: list[dict] = []  # backward-compat shadow
        self._max_entries = max_entries
        self._path = path or Path("data/brain_memory.json")
        self._total_prana_spent: int = 0
        self._suppressed_posts: list[dict] = []  # 12D: tracks Brain-offline skips

    def record(
        self, thought: object, heartbeat: int, *, posted: bool = False,
    ) -> int:
        """Record a thought. Returns the prana cost of this cell.

        Creates a MahaCellUnified wrapping the Thought, then appends
        the backward-compatible dict entry. FIFO eviction if over capacity.
        """
        from city.brain_cell import create_brain_cell, get_cell_prana_cost

        kind = getattr(thought, "kind", "comprehension")
        cell = create_brain_cell(
            thought, heartbeat, kind=kind, posted=posted,
        )
        cost = get_cell_prana_cost(cell)
        self._total_prana_spent += cost

        self._cells.append(cell)
        self._entries.append({
            "thought": thought.to_dict(),  # type: ignore[union-attr]
            "heartbeat": heartbeat,
            "posted": posted,
        })

        # FIFO eviction (hard cap)
        while len(self._cells) > self._max_entries:
            self._cells.pop(0)
            self._entries.pop(0)

        return cost

    def record_external(self, feedback: dict) -> None:
        """Record an externally-observed brain thought (from discussion scan).

        External thoughts cost 0 prana (not generated by our LLM).
        Adds source="external" to distinguish from internally-recorded thoughts.
        """
        from city.brain_cell import create_brain_cell_from_dict

        heartbeat = feedback.get("heartbeat", 0)
        cell = create_brain_cell_from_dict(
            feedback, heartbeat, source="external",
        )
        self._cells.append(cell)
        self._entries.append({
            "thought": feedback,
            "heartbeat": heartbeat,
            "posted": True,
            "source": "external",
        })

        # FIFO eviction
        while len(self._cells) > self._max_entries:
            self._cells.pop(0)
            self._entries.pop(0)

    def decay(self, current_heartbeat: int) -> int:
        """Soft relevance decay — knowledge persists, ranking changes.

        Reorders cells by relevance score (newest + most relevant first).
        No cells are killed. Only FIFO eviction (hard cap) removes cells.
        Returns 0 (no cells reaped — kept for backward compat).
        """
        from city.brain_cell import cell_relevance

        if not self._cells:
            return 0

        # Score each cell by relevance
        scored = [
            (cell_relevance(cell, current_heartbeat), i, cell, entry)
            for i, (cell, entry) in enumerate(zip(self._cells, self._entries))
        ]
        # Sort by relevance descending, then by original order (stable)
        scored.sort(key=lambda x: (-x[0], x[1]))

        self._cells = [s[2] for s in scored]
        self._entries = [s[3] for s in scored]

        lowest = scored[-1][0] if scored else 1.0
        logger.debug(
            "BrainMemory: decay pass, %d cells, lowest relevance=%.3f",
            len(self._cells), lowest,
        )
        return 0

    def recent(self, n: int = 6) -> list[dict]:
        """Return the N most recent entries (newest last)."""
        return self._entries[-n:]

    def pattern_summary(self) -> str:
        """Human-readable summary of recent thought patterns."""
        if not self._entries:
            return "No brain thoughts recorded yet."
        recent = self.recent(6)
        confidences = [
            e["thought"].get("confidence", 0.0) for e in recent
        ]
        avg = sum(confidences) / len(confidences) if confidences else 0.0
        high = sum(1 for c in confidences if c >= 0.7)
        return (
            f"{high}/{len(recent)} thoughts had high confidence, "
            f"avg {avg:.2f}"
        )

    @property
    def total_prana_spent(self) -> int:
        """Total prana spent on brain calls this session."""
        return self._total_prana_spent

    @property
    def cell_count(self) -> int:
        """Number of live cells in memory."""
        return len(self._cells)

    # ── 12D: Suppressed Posts Ledger ────────────────────────────────

    def record_suppressed(
        self, agent_name: str, discussion_number: int, heartbeat: int,
        reason: str = "brain_offline",
    ) -> None:
        """12D: Record a post that was suppressed because Brain was offline.

        Persisted so the Brain can detect its own gaps on recovery.
        Capped at 50 entries to prevent unbounded growth during long outages.
        """
        self._suppressed_posts.append({
            "agent": agent_name,
            "discussion": discussion_number,
            "heartbeat": heartbeat,
            "reason": reason,
        })
        # Hard cap — oldest entries evicted first
        if len(self._suppressed_posts) > 50:
            self._suppressed_posts = self._suppressed_posts[-50:]
        logger.debug(
            "BrainMemory: recorded suppressed post for %s on #%d (reason=%s)",
            agent_name, discussion_number, reason,
        )

    def get_suppressed(self) -> list[dict]:
        """12D: Return all suppressed posts (Brain was offline)."""
        return list(self._suppressed_posts)

    def clear_suppressed(self) -> int:
        """12D: Clear suppressed posts ledger after Brain has processed them.

        Returns the number of entries cleared.
        """
        count = len(self._suppressed_posts)
        self._suppressed_posts.clear()
        if count:
            logger.info("BrainMemory: cleared %d suppressed posts", count)
        return count

    def flush(self) -> None:
        """Persist to disk."""
        try:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            payload = {
                "entries": self._entries,
                "suppressed": self._suppressed_posts,
            }
            self._path.write_text(json.dumps(payload, indent=2))
            logger.debug("BrainMemory: flushed %d entries", len(self._entries))
        except Exception as e:
            logger.warning("BrainMemory: flush failed: %s", e)

    def load(self) -> None:
        """Load from disk. Recreates cells from persisted entries.

        Silently starts empty if file missing.
        """
        if not self._path.exists():
            return
        try:
            raw = json.loads(self._path.read_text())
            # 12D: Support both old format (list) and new format (dict)
            if isinstance(raw, dict):
                data = raw.get("entries", [])
                self._suppressed_posts = raw.get("suppressed", [])
            elif isinstance(raw, list):
                data = raw
            else:
                data = []
            if isinstance(data, list):
                self._entries = data[-self._max_entries :]
                # Recreate cells from entries
                self._cells = []
                from city.brain_cell import (
                    create_brain_cell_from_dict,
                )
                for entry in self._entries:
                    source = entry.get("source", "internal")
                    cell = create_brain_cell_from_dict(
                        entry.get("thought", {}),
                        entry.get("heartbeat", 0),
                        kind=entry.get("thought", {}).get(
                            "kind", "comprehension",
                        ),
                        posted=entry.get("posted", False),
                        source=source,
                    )
                    self._cells.append(cell)
                logger.info(
                    "BrainMemory: loaded %d entries (%d cells) from %s",
                    len(self._entries),
                    len(self._cells),
                    self._path,
                )
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("BrainMemory: load failed: %s", e)
