"""
BRAIN MEMORY — MahaCellUnified Population for Brain Thoughts.

Phase 6B: BrainMemory is now a cell population with TTL-based decay.
Each thought is a MahaCellUnified[BrainCellPayload] with prana cost
and integrity-based lifespan. Dead cells are reaped on decay().

Backward-compatible API: record(), recent(), pattern_summary(),
flush(), load() all work identically to the flat FIFO.

Loaded at boot, flushed in MOKSHA. Same persistence pattern as mayor_state.json.

    Hare Krishna Hare Krishna Krishna Krishna Hare Hare
    Hare Rama   Hare Rama   Rama   Rama   Hare Hare
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger("AGENT_CITY.BRAIN_MEMORY")

_DEFAULT_MAX_ENTRIES = 24  # ~6 hours at current heartbeat rate


class BrainMemory:
    """MahaCellUnified population for brain thoughts.

    Each entry is backed by a BrainCell (MahaCellUnified[BrainCellPayload]).
    TTL-based decay: cells die after BRAIN_CELL_TTL heartbeats.
    FIFO eviction when len > max_entries (hard cap).

    Backward-compatible: record/recent/pattern_summary/flush/load
    all return the same dict format as the original flat FIFO.
    """

    __slots__ = ("_cells", "_entries", "_max_entries", "_path",
                 "_total_prana_spent")

    def __init__(
        self,
        path: Path | None = None,
        max_entries: int = _DEFAULT_MAX_ENTRIES,
    ) -> None:
        self._cells: list = []  # list[MahaCellUnified[BrainCellPayload]]
        self._entries: list[dict] = []  # backward-compat shadow
        self._max_entries = max_entries
        self._path = path or Path("data/brain_memory.json")
        self._total_prana_spent: int = 0

    def record(
        self, thought: object, heartbeat: int, *, posted: bool = False,
    ) -> int:
        """Record a thought. Returns the prana cost of this cell.

        Creates a MahaCellUnified wrapping the Thought, then appends
        the backward-compatible dict entry. FIFO eviction if over capacity.
        """
        from city.brain_cell import create_brain_cell, get_cell_prana_cost

        kind = getattr(thought, "kind", "comprehension")
        cell = create_brain_cell(
            thought, heartbeat, kind=kind, posted=posted,
        )
        cost = get_cell_prana_cost(cell)
        self._total_prana_spent += cost

        self._cells.append(cell)
        self._entries.append({
            "thought": thought.to_dict(),  # type: ignore[union-attr]
            "heartbeat": heartbeat,
            "posted": posted,
        })

        # FIFO eviction (hard cap)
        while len(self._cells) > self._max_entries:
            self._cells.pop(0)
            self._entries.pop(0)

        return cost

    def record_external(self, feedback: dict) -> None:
        """Record an externally-observed brain thought (from discussion scan).

        External thoughts cost 0 prana (not generated by our LLM).
        Adds source="external" to distinguish from internally-recorded thoughts.
        """
        from city.brain_cell import create_brain_cell_from_dict

        heartbeat = feedback.get("heartbeat", 0)
        cell = create_brain_cell_from_dict(
            feedback, heartbeat, source="external",
        )
        self._cells.append(cell)
        self._entries.append({
            "thought": feedback,
            "heartbeat": heartbeat,
            "posted": True,
            "source": "external",
        })

        # FIFO eviction
        while len(self._cells) > self._max_entries:
            self._cells.pop(0)
            self._entries.pop(0)

    def decay(self, current_heartbeat: int) -> int:
        """Reap dead cells whose TTL has expired.

        Returns the number of cells reaped.
        Called in MOKSHA phase to prune stale thoughts.
        """
        from city.brain_cell import is_cell_alive

        alive_cells = []
        alive_entries = []
        reaped = 0

        for cell, entry in zip(self._cells, self._entries):
            if is_cell_alive(cell, current_heartbeat):
                alive_cells.append(cell)
                alive_entries.append(entry)
            else:
                reaped += 1

        self._cells = alive_cells
        self._entries = alive_entries

        if reaped:
            logger.debug(
                "BrainMemory: decayed %d cells, %d alive",
                reaped, len(self._cells),
            )
        return reaped

    def recent(self, n: int = 6) -> list[dict]:
        """Return the N most recent entries (newest last)."""
        return self._entries[-n:]

    def pattern_summary(self) -> str:
        """Human-readable summary of recent thought patterns."""
        if not self._entries:
            return "No brain thoughts recorded yet."
        recent = self.recent(6)
        confidences = [
            e["thought"].get("confidence", 0.0) for e in recent
        ]
        avg = sum(confidences) / len(confidences) if confidences else 0.0
        high = sum(1 for c in confidences if c >= 0.7)
        return (
            f"{high}/{len(recent)} thoughts had high confidence, "
            f"avg {avg:.2f}"
        )

    @property
    def total_prana_spent(self) -> int:
        """Total prana spent on brain calls this session."""
        return self._total_prana_spent

    @property
    def cell_count(self) -> int:
        """Number of live cells in memory."""
        return len(self._cells)

    def flush(self) -> None:
        """Persist to disk."""
        try:
            self._path.parent.mkdir(parents=True, exist_ok=True)
            self._path.write_text(json.dumps(self._entries, indent=2))
            logger.debug("BrainMemory: flushed %d entries", len(self._entries))
        except Exception as e:
            logger.warning("BrainMemory: flush failed: %s", e)

    def load(self) -> None:
        """Load from disk. Recreates cells from persisted entries.

        Silently starts empty if file missing.
        """
        if not self._path.exists():
            return
        try:
            data = json.loads(self._path.read_text())
            if isinstance(data, list):
                self._entries = data[-self._max_entries :]
                # Recreate cells from entries
                self._cells = []
                from city.brain_cell import (
                    create_brain_cell_from_dict,
                )
                for entry in self._entries:
                    source = entry.get("source", "internal")
                    cell = create_brain_cell_from_dict(
                        entry.get("thought", {}),
                        entry.get("heartbeat", 0),
                        kind=entry.get("thought", {}).get(
                            "kind", "comprehension",
                        ),
                        posted=entry.get("posted", False),
                        source=source,
                    )
                    self._cells.append(cell)
                logger.info(
                    "BrainMemory: loaded %d entries (%d cells) from %s",
                    len(self._entries),
                    len(self._cells),
                    self._path,
                )
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("BrainMemory: load failed: %s", e)
