"""
BRAIN CELL — MahaCellUnified Wrapper for Brain Thoughts.

Wraps Thought in a MahaCellUnified with:
- MahaHeader: 72-byte routing (source=brain, target=city)
- CellLifecycleState: prana cost per thought, TTL-based decay
- Payload: Thought dict + metadata

Phase 6B: BrainMemory becomes a cell population with decay.
BrainPromptHeader → MahaCell-aware header with live prana stats.

    Hare Krishna Hare Krishna Krishna Krishna Hare Hare
    Hare Rama   Hare Rama   Rama   Rama   Hare Hare
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from vibe_core.mahamantra.protocols._header import MahaHeader
from vibe_core.mahamantra.substrate.cell_system.cell import (
    CellLifecycleState,
    MahaCellUnified,
)

from city.seed_constants import NAVA, TRINITY

if TYPE_CHECKING:
    from city.brain import Thought, ThoughtKind

logger = logging.getLogger("AGENT_CITY.BRAIN_CELL")

# ── Prana Costs (Mahamantra-derived) ─────────────────────────────────────
# Each brain call costs NAVA (9) prana from the city treasury.
# Health checks cost TRINITY (3) — lightweight system monitoring.
# Max 3 calls per KARMA cycle (existing budget from brain_health handler).

BRAIN_CALL_COST: int = NAVA  # 9 prana per LLM invocation
BRAIN_HEALTH_COST: int = TRINITY  # 3 prana for health check (cheaper)

# TTL for brain cells: thoughts decay after this many heartbeats.
# NAVA × TRINITY = 27 heartbeats (~6.75 hours at 15min intervals).
BRAIN_CELL_TTL: int = NAVA * TRINITY  # 27 heartbeats

# ── Brain Address (deterministic) ────────────────────────────────────────
# Source address for all brain-originated cells.
_BRAIN_SOURCE_ADDRESS: int = 137  # MAHA_QUANTUM — the brain's address


@dataclass(frozen=True)
class BrainCellPayload:
    """Payload carried by a brain MahaCellUnified.

    Wraps the Thought dict with metadata for the cell population.
    """

    thought: dict = field(default_factory=dict)
    heartbeat: int = 0
    kind: str = "comprehension"
    posted: bool = False
    source: str = "internal"  # "internal" or "external"
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        """Serialize for JSON persistence."""
        return {
            "thought": self.thought,
            "heartbeat": self.heartbeat,
            "kind": self.kind,
            "posted": self.posted,
            "source": self.source,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, data: dict) -> BrainCellPayload:
        """Deserialize from JSON."""
        return cls(
            thought=data.get("thought", {}),
            heartbeat=data.get("heartbeat", 0),
            kind=data.get("kind", "comprehension"),
            posted=data.get("posted", False),
            source=data.get("source", "internal"),
            created_at=data.get("created_at", 0.0),
        )


def create_brain_cell(
    thought: Thought,
    heartbeat: int,
    *,
    kind: ThoughtKind | str = "comprehension",
    posted: bool = False,
    source: str = "internal",
) -> MahaCellUnified[BrainCellPayload]:
    """Create a MahaCellUnified wrapping a brain Thought.

    The cell carries:
    - MahaHeader: brain → city routing
    - CellLifecycleState: prana = cost of this thought, active = True
    - BrainCellPayload: the thought data + metadata
    """
    kind_str = kind.value if hasattr(kind, "value") else str(kind)

    header = MahaHeader.create(
        source=_BRAIN_SOURCE_ADDRESS,
        target=0,  # broadcast to city
        operation=hash(kind_str) & 0xFFFF,
    )

    cost = BRAIN_HEALTH_COST if kind_str == "health_check" else BRAIN_CALL_COST

    lifecycle = CellLifecycleState(
        prana=cost,
        integrity=BRAIN_CELL_TTL,
        cycle=heartbeat,
        is_active=True,
    )

    payload = BrainCellPayload(
        thought=thought.to_dict(),
        heartbeat=heartbeat,
        kind=kind_str,
        posted=posted,
        source=source,
    )

    cell = MahaCellUnified(
        header=header,
        lifecycle=lifecycle,
        payload=payload,
    )
    logger.debug(
        "BrainCell created: kind=%s heartbeat=%d cost=%d",
        kind_str, heartbeat, cost,
    )
    return cell


def create_brain_cell_from_dict(
    thought_dict: dict,
    heartbeat: int,
    *,
    kind: str = "comprehension",
    posted: bool = False,
    source: str = "external",
) -> MahaCellUnified[BrainCellPayload]:
    """Create a BrainCell from a raw thought dict (external feedback).

    Used for record_external() — thoughts observed from discussions,
    not generated by the brain.
    """
    header = MahaHeader.create(
        source=0,  # external source
        target=_BRAIN_SOURCE_ADDRESS,  # routed TO the brain
        operation=hash(kind) & 0xFFFF,
    )

    lifecycle = CellLifecycleState(
        prana=0,  # external thoughts cost nothing
        integrity=BRAIN_CELL_TTL,
        cycle=heartbeat,
        is_active=True,
    )

    payload = BrainCellPayload(
        thought=thought_dict,
        heartbeat=heartbeat,
        kind=kind,
        posted=posted,
        source=source,
    )

    return MahaCellUnified(
        header=header,
        lifecycle=lifecycle,
        payload=payload,
    )


def is_cell_alive(
    cell: MahaCellUnified[BrainCellPayload],
    current_heartbeat: int,
) -> bool:
    """Check if a brain cell is still alive (within TTL).

    Cells decay after BRAIN_CELL_TTL heartbeats.
    """
    if not cell.lifecycle.is_active:
        return False
    birth_heartbeat = cell.lifecycle.cycle
    age = current_heartbeat - birth_heartbeat
    return age < cell.lifecycle.integrity


def get_cell_prana_cost(
    cell: MahaCellUnified[BrainCellPayload],
) -> int:
    """Get the prana cost of this brain cell."""
    return cell.lifecycle.prana
