"""
GitStateAuthority — Single Gatekeeper for Repository Mutations
==============================================================

The ONLY layer in Agent City that touches git.  Every agent, every process,
every heartbeat goes through here.  Reads file classification from
config/city.yaml (the SSOT) and enforces three rules:

  1. Runtime files are NEVER committed  (auto-ignored)
  2. Protected files are IMMUTABLE      (hash-verified)
  3. Security patterns NEVER enter git  (blocked at stage)

Also handles:
  - .gitignore generation from config (no manual maintenance)
  - Graceful GPG degradation for async heartbeat signing (OPUS-092)
"""

import hashlib
import json
import logging
import subprocess
from fnmatch import fnmatch
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger("AGENT_CITY.GIT")

HASH_FILE = "scripts/governance/core_hashes.json"

_GITIGNORE_HEADER = """\
# ==========================================================================
# AUTO-GENERATED by GitStateAuthority from config/city.yaml
# Do NOT edit manually. Run: python -m city.git_client sync
# ==========================================================================
"""


class GitStateAuthority:
    """Single point of git mutation for Agent City.

    Reads config/city.yaml git section to classify every file as:
      - runtime:   ephemeral, auto-ignored, never staged
      - security:  forbidden, never enters repo
      - protected: immutable core, hash-verified before commit
      - code:      everything else, normal workflow
    """

    def __init__(self, workspace: Optional[Path] = None, config: Optional[dict] = None):
        self._workspace = workspace or Path.cwd()
        self._config = config or self._load_config()
        self._git_cfg = self._config.get("git", {})
        self._gpg_available = self._check_gpg_key_available()

    # ── Config ─────────────────────────────────────────────────────────────

    def _load_config(self) -> dict:
        try:
            from config import get_config
            return get_config()
        except Exception:
            return {}

    @property
    def runtime_patterns(self) -> List[str]:
        return self._git_cfg.get("runtime_patterns", [])

    @property
    def security_patterns(self) -> List[str]:
        return self._git_cfg.get("security_patterns", [])

    @property
    def protected_files(self) -> List[str]:
        return self._git_cfg.get("protected_files", [])

    # ── Classification ──────────────────────────────────────────────────────

    @staticmethod
    def _matches(path: str, pattern: str) -> bool:
        """Git-style pattern match. Handles **/ prefix by matching basename too."""
        if fnmatch(path, pattern):
            return True
        # **/ means "any directory depth" — match against basename
        if pattern.startswith("**/"):
            return fnmatch(path, pattern[3:]) or fnmatch(path.split("/")[-1], pattern[3:])
        return False

    def classify(self, path: str) -> str:
        """Classify a file path: 'security' | 'runtime' | 'protected' | 'code'."""
        for pattern in self.security_patterns:
            if self._matches(path, pattern):
                return "security"
        for pattern in self.runtime_patterns:
            if self._matches(path, pattern):
                return "runtime"
        if path in self.protected_files:
            return "protected"
        return "code"

    def is_blocked(self, path: str) -> bool:
        """Return True if a file must never be staged."""
        return self.classify(path) in ("security", "runtime")

    # ── .gitignore Generation ─────────────────────────────────────────────

    def generate_gitignore(self) -> str:
        """Generate .gitignore content from city.yaml config."""
        lines = [_GITIGNORE_HEADER]

        lines.append("# Security — NEVER enter the repo")
        for p in self.security_patterns:
            lines.append(p)
        lines.append("")

        lines.append("# Runtime state — ephemeral, changes every tick")
        for p in self.runtime_patterns:
            lines.append(p)
        lines.append("")

        lines.append("# Standard Python / tooling")
        for p in [
            "*.so", "build/", "dist/", "*.egg-info/", "*.egg",
            ".venv/", "venv/", "env/",
            ".coverage", "htmlcov/", ".tox/", ".nox/",
            ".hypothesis/", "cover/",
            ".idea/", ".vscode/", "*.swp", "*.swo", "*~",
            ".cursorignore", ".cursorindexingignore",
        ]:
            lines.append(p)
        lines.append("")

        return "\n".join(lines) + "\n"

    def sync_gitignore(self) -> bool:
        """Write .gitignore from config. Returns True if changed."""
        gitignore_path = self._workspace / ".gitignore"
        new_content = self.generate_gitignore()
        if gitignore_path.exists() and gitignore_path.read_text() == new_content:
            return False
        gitignore_path.write_text(new_content)
        logger.info("GitStateAuthority: .gitignore synced from city.yaml")
        return True

    # ── Protected File Integrity ─────────────────────────────────────────

    def compute_hash(self, path: str) -> str:
        """SHA256 hash of a file."""
        full = self._workspace / path
        if not full.exists():
            return "FILE_NOT_FOUND"
        return hashlib.sha256(full.read_bytes()).hexdigest()

    def compute_protected_hashes(self) -> Dict[str, str]:
        """Compute current SHA256 hashes for all protected files."""
        return {f: self.compute_hash(f) for f in self.protected_files}

    def save_hashes(self) -> Path:
        """Snapshot current protected file hashes to disk."""
        hashes = self.compute_protected_hashes()
        hash_path = self._workspace / HASH_FILE
        hash_path.parent.mkdir(parents=True, exist_ok=True)
        hash_path.write_text(json.dumps(hashes, indent=2) + "\n")
        logger.info("GitStateAuthority: Protected hashes saved to %s", HASH_FILE)
        return hash_path

    def verify_protected(self) -> List[str]:
        """Verify protected files against saved hashes. Returns list of violations."""
        hash_path = self._workspace / HASH_FILE
        if not hash_path.exists():
            logger.warning("GitStateAuthority: No hash file found at %s — run save_hashes() first", HASH_FILE)
            return []
        expected = json.loads(hash_path.read_text())
        violations = []
        for path, expected_hash in expected.items():
            current = self.compute_hash(path)
            if current != expected_hash:
                violations.append(path)
                logger.warning("INTEGRITY VIOLATION: %s (expected %s..., got %s...)",
                               path, expected_hash[:12], current[:12])
        return violations

    # ── GPG (Deploy-Concern) ─────────────────────────────────────────────

    def _check_gpg_key_available(self) -> bool:
        """Non-interactive GPG sign test with timeout. Deploy-concern only."""
        try:
            result = subprocess.run(
                ["gpg", "--batch", "--pinentry-mode", "error",
                 "--sign", "--default-key", "", "-o", "/dev/null"],
                input=b"test",
                cwd=str(self._workspace),
                capture_output=True,
                timeout=5,
            )
            if result.returncode == 0:
                logger.info("GitStateAuthority: GPG signing operational.")
                return True
            return False
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            return False

    # ── Git Operations (Gated) ──────────────────────────────────────────

    def is_dirty(self) -> bool:
        """Check if the workspace has uncommitted changes."""
        try:
            result = subprocess.run(
                ["git", "status", "--porcelain"],
                cwd=str(self._workspace),
                capture_output=True, text=True, check=True,
            )
            return bool(result.stdout.strip())
        except subprocess.CalledProcessError:
            return False

    def stage(self, paths: List[str]) -> bool:
        """Stage paths, rejecting any runtime/security files."""
        blocked = [p for p in paths if self.is_blocked(p)]
        if blocked:
            logger.error("GitStateAuthority: BLOCKED staging of runtime/security files: %s", blocked)
            return False
        safe = [p for p in paths if not self.is_blocked(p)]
        if not safe:
            return True
        try:
            subprocess.run(
                ["git", "add"] + safe,
                cwd=str(self._workspace),
                check=True,
            )
            return True
        except subprocess.CalledProcessError as e:
            logger.error("Failed to stage files: %s", e)
            return False

    def commit(self, message: str, paths: Optional[List[str]] = None, force_unsigned: bool = False) -> bool:
        """Commit with governance: verify protected integrity, block runtime, GPG if available."""
        if paths:
            if not self.stage(paths):
                return False

        if not self.is_dirty():
            logger.info("GitStateAuthority: Nothing to commit.")
            return True

        violations = self.verify_protected()
        if violations:
            logger.error("GitStateAuthority: COMMIT BLOCKED — protected file integrity violated: %s", violations)
            return False

        cmd = ["git", "commit", "-m", message]
        if self._gpg_available and not force_unsigned:
            cmd.append("-S")

        try:
            subprocess.run(
                cmd,
                cwd=str(self._workspace),
                capture_output=True, text=True, check=True,
            )
            logger.info("GitStateAuthority: Committed '%s'", message)
            return True
        except subprocess.CalledProcessError as e:
            logger.error("GitStateAuthority: Commit failed: %s", e.stderr)
            return False


if __name__ == "__main__":
    import sys
    gsa = GitStateAuthority()
    if len(sys.argv) > 1 and sys.argv[1] == "sync":
        gsa.sync_gitignore()
        gsa.save_hashes()
        print("GitStateAuthority: .gitignore + hashes synced from city.yaml")
    else:
        print("Usage: python -m city.git_client sync")
