"""
CityReactor — Self-Awareness for Agent City.

Issue #17 Stufe 2b: Pain detection + automatic intent generation.

The system FEELS when something hurts and generates CityIntents
that CityAttention routes to handlers. No manual triggering.

Inspired by steward-protocol's ReactorProtocol (drift detection → reflection).

    Hare Krishna Hare Krishna Krishna Krishna Hare Hare
    Hare Rama   Hare Rama   Rama   Rama   Hare Hare
"""

from __future__ import annotations

import logging
from collections import deque
from dataclasses import dataclass, field
from typing import Any, Deque, Dict, List, Optional

logger = logging.getLogger("AGENT_CITY.REACTOR")

# =============================================================================
# THRESHOLDS (configurable later via city.yaml)
# =============================================================================

METABOLIZE_SLOW_MS = 500.0  # Pain if metabolize_all > 500ms
METABOLIZE_SLOW_CONSECUTIVE = 3  # Must be slow N times in a row
DEATH_SPIKE_THRESHOLD = 5  # Pain if >= N agents die in one cycle
ZONE_EMPTY_THRESHOLD = 0  # Pain if any zone has <= N agents

# History window for rolling metrics
METRIC_WINDOW = 10


# =============================================================================
# CITY INTENT
# =============================================================================


@dataclass(frozen=True)
class CityIntent:
    """A pain signal generated by CityReactor.

    Routed by CityAttention to the appropriate handler.
    """

    signal: str  # Intent key (matches CityAttention registration)
    priority: str = "normal"  # critical, high, normal, low
    context: Dict[str, Any] = field(default_factory=dict)


# =============================================================================
# CITY REACTOR
# =============================================================================


class CityReactor:
    """Self-awareness engine for Agent City.

    Records operational metrics, detects pain patterns,
    and generates CityIntents for CityAttention to route.

    Pain detection rules:
    - metabolize_slow: metabolize_all > 500ms for 3 consecutive runs
    - agent_death_spike: >= 5 agent deaths in one cycle
    - zone_empty: any zone with 0 agents
    - contract_failing: contract check failures (future)
    """

    def __init__(self) -> None:
        # Rolling metric windows
        self._metabolize_times: Deque[float] = deque(maxlen=METRIC_WINDOW)
        self._last_death_count: int = 0
        self._last_zone_pop: Dict[str, int] = {}

        # Pending pain signals (consumed on detect_pain())
        self._pending_pain: List[CityIntent] = []

        # Stats
        self._total_records: int = 0
        self._total_pain: int = 0

    def record(self, metric: str, **kwargs: Any) -> None:
        """Record an operational metric.

        Args:
            metric: Metric name (metabolize_all, agent_deaths, zone_population)
            **kwargs: Metric-specific values
        """
        self._total_records += 1

        if metric == "metabolize_all":
            duration_ms = kwargs.get("duration_ms", 0.0)
            self._metabolize_times.append(duration_ms)
            self._check_metabolize_pain()

        elif metric == "agent_deaths":
            count = kwargs.get("count", 0)
            self._last_death_count = count
            self._check_death_spike_pain()

        elif metric == "zone_population":
            zones = kwargs.get("zones", {})
            self._last_zone_pop = zones
            self._check_zone_empty_pain()

    def detect_pain(self) -> List[CityIntent]:
        """Consume and return all pending pain signals.

        Returns:
            List of CityIntents to route via CityAttention.
            Empty list if system is healthy.
        """
        pain = list(self._pending_pain)
        self._pending_pain.clear()
        return pain

    def stats(self) -> Dict[str, Any]:
        """Return reactor statistics."""
        return {
            "total_records": self._total_records,
            "pain_detected": self._total_pain,
            "metabolize_window": list(self._metabolize_times),
            "last_death_count": self._last_death_count,
            "last_zone_pop": self._last_zone_pop,
            "pending_pain": len(self._pending_pain),
        }

    # ── Pain detection rules ──────────────────────────────────────────

    def _check_metabolize_pain(self) -> None:
        """Check if metabolize_all has been slow N× in a row."""
        times = list(self._metabolize_times)
        if len(times) < METABOLIZE_SLOW_CONSECUTIVE:
            return

        # Check last N runs
        recent = times[-METABOLIZE_SLOW_CONSECUTIVE:]
        if all(t > METABOLIZE_SLOW_MS for t in recent):
            avg = sum(recent) / len(recent)
            self._emit_pain(CityIntent(
                signal="metabolize_slow",
                priority="high",
                context={
                    "avg_ms": round(avg, 1),
                    "consecutive": METABOLIZE_SLOW_CONSECUTIVE,
                    "threshold_ms": METABOLIZE_SLOW_MS,
                },
            ))
            logger.warning(
                "PAIN: metabolize_all slow %d× in a row (avg %.1fms > %.1fms)",
                METABOLIZE_SLOW_CONSECUTIVE, avg, METABOLIZE_SLOW_MS,
            )

    def _check_death_spike_pain(self) -> None:
        """Check if too many agents died in one cycle."""
        if self._last_death_count >= DEATH_SPIKE_THRESHOLD:
            self._emit_pain(CityIntent(
                signal="agent_death_spike",
                priority="critical",
                context={
                    "deaths": self._last_death_count,
                    "threshold": DEATH_SPIKE_THRESHOLD,
                },
            ))
            logger.warning(
                "PAIN: %d agent deaths in one cycle (threshold: %d)",
                self._last_death_count, DEATH_SPIKE_THRESHOLD,
            )

    def _check_zone_empty_pain(self) -> None:
        """Check if any zone has 0 agents."""
        for zone, pop in self._last_zone_pop.items():
            if pop <= ZONE_EMPTY_THRESHOLD:
                self._emit_pain(CityIntent(
                    signal="zone_empty",
                    priority="high",
                    context={"zone": zone, "population": pop},
                ))
                logger.warning("PAIN: zone '%s' is empty", zone)

    def _emit_pain(self, intent: CityIntent) -> None:
        """Add a pain signal to the pending queue."""
        self._pending_pain.append(intent)
        self._total_pain += 1
